services:
  - type: web
    name: casar-proxy
    runtime: docker
    plan: free

    healthCheckPath: /

    autoDeploy: true

    envVars:
      - key: CASAR_HOST
        value: noivos.casar.com
      - key: CASAR_PATH
        value: /mariafernandaeronaldo
      - key: CASAR_PAINEL_HOST
        value: painel.casar.com
      - key: SITE_URL
        value: https://mariafernandaeronaldo.com.br
